name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    env:
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run Foundry Unit Tests
        run: forge test --nmc 'ProtocolIntegration|EndToEnd' -vv

  foundry_integration_tests:
    runs-on: ubuntu-latest
    env:
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      FOUNDRY_FUZZ_RUNS: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run Foundry Integration Tests
        run: forge test --mc ProtocolIntegration -vv
